/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package corvex;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import org.python.util.PythonInterpreter;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import javax.swing.JFileChooser;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.text.AbstractDocument;
import java.util.*;

/**
 *
 * @author nihil
 */
public class Ventana extends javax.swing.JFrame {
    NumeroLinea numerolinea;
    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    
    //Variables Globales
    //static String direccionDanielAuto="C:\\Users\\alexi\\OneDrive\\Escritorio\\uni\\compiladores\\entrega5\\Corvex\\python\\automata.py";
    static String direccionDanielAuto="C:\\Users\\bukch\\Desktop\\univrsidad\\compilador\\Corvex\\python\\automata.py";
    //static String direccionDanielError="C:\\Users\\alexi\\OneDrive\\Escritorio\\uni\\compiladores\\entrega5\\Corvex\\error.txt";
    static String direccionDanielError="C:\\Users\\bukch\\Desktop\\univrsidad\\compilador\\Corvex\\error.txt";

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        inicializar();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("CORVEX IDE v1.5");
        pintarColores();

    }
    
    private void inicializar(){
        numerolinea = new NumeroLinea(jTextPaneCodigo);
        jScrollPane1.setRowHeaderView(numerolinea);
    } 
    

    //Funciones para abrir archivos
    public String abrirArchivo(File archivo) {
        String documento = "";
        try {
            entrada = new FileInputStream(archivo);
            int ascii;
            while ((ascii = entrada.read()) != -1) {
                char caracter = (char) ascii;
                documento += caracter;
                
            }

        } catch (IOException e) {
        }
        return documento;
    }
  

    public String guardarArchivo(File archivo, String documento) {
        String msj = null;
        try {
            salida = new FileOutputStream(archivo);
            byte[] bytxt = documento.getBytes();
            salida.write(bytxt);
            msj = "Archivo Guardado Correctamente";
        } catch (IOException e) {
        }
        return msj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneCodigo = new javax.swing.JTextPane();
        jTabbedPaneTypes = new javax.swing.JTabbedPane();
        jPanelLexico = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaLexico = new javax.swing.JTextArea();
        jPanelSintactico = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaSintactoco = new javax.swing.JTextArea();
        jPanelSemantico = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaSemantico = new javax.swing.JTextArea();
        jPanelCI = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaCI = new javax.swing.JTextArea();
        jTabbedPaneResultados = new javax.swing.JTabbedPane();
        jPanelErrores = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaErrores = new javax.swing.JTextArea();
        jPanelResultados = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaResultados = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemArchivo = new javax.swing.JMenuItem();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuFormato = new javax.swing.JMenu();
        jMenuCompilar = new javax.swing.JMenu();
        jMenuItemComp = new javax.swing.JMenuItem();
        jMenuItemDebug = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setBackground(new java.awt.Color(21, 30, 33));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextPaneCodigo.setBackground(new java.awt.Color(150, 150, 150));
        jTextPaneCodigo.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextPaneCodigo.setForeground(new java.awt.Color(0, 51, 102));
        jScrollPane1.setViewportView(jTextPaneCodigo);

        jPanelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 780, 470));

        jTextAreaLexico.setEditable(false);
        jTextAreaLexico.setBackground(new java.awt.Color(150, 150, 150));
        jTextAreaLexico.setColumns(20);
        jTextAreaLexico.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextAreaLexico.setForeground(new java.awt.Color(0, 51, 51));
        jTextAreaLexico.setRows(5);
        jScrollPane2.setViewportView(jTextAreaLexico);

        javax.swing.GroupLayout jPanelLexicoLayout = new javax.swing.GroupLayout(jPanelLexico);
        jPanelLexico.setLayout(jPanelLexicoLayout);
        jPanelLexicoLayout.setHorizontalGroup(
            jPanelLexicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        jPanelLexicoLayout.setVerticalGroup(
            jPanelLexicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        jTabbedPaneTypes.addTab("Léxico", jPanelLexico);

        jTextAreaSintactoco.setEditable(false);
        jTextAreaSintactoco.setBackground(new java.awt.Color(150, 150, 150));
        jTextAreaSintactoco.setColumns(20);
        jTextAreaSintactoco.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextAreaSintactoco.setForeground(new java.awt.Color(0, 51, 51));
        jTextAreaSintactoco.setRows(5);
        jScrollPane3.setViewportView(jTextAreaSintactoco);

        javax.swing.GroupLayout jPanelSintacticoLayout = new javax.swing.GroupLayout(jPanelSintactico);
        jPanelSintactico.setLayout(jPanelSintacticoLayout);
        jPanelSintacticoLayout.setHorizontalGroup(
            jPanelSintacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        jPanelSintacticoLayout.setVerticalGroup(
            jPanelSintacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        jTabbedPaneTypes.addTab("Sintáctico", jPanelSintactico);

        jTextAreaSemantico.setEditable(false);
        jTextAreaSemantico.setBackground(new java.awt.Color(150, 150, 150));
        jTextAreaSemantico.setColumns(20);
        jTextAreaSemantico.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextAreaSemantico.setForeground(new java.awt.Color(0, 51, 51));
        jTextAreaSemantico.setRows(5);
        jScrollPane4.setViewportView(jTextAreaSemantico);

        javax.swing.GroupLayout jPanelSemanticoLayout = new javax.swing.GroupLayout(jPanelSemantico);
        jPanelSemantico.setLayout(jPanelSemanticoLayout);
        jPanelSemanticoLayout.setHorizontalGroup(
            jPanelSemanticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        jPanelSemanticoLayout.setVerticalGroup(
            jPanelSemanticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );

        jTabbedPaneTypes.addTab("Semántico", jPanelSemantico);

        jTextAreaCI.setEditable(false);
        jTextAreaCI.setBackground(new java.awt.Color(150, 150, 150));
        jTextAreaCI.setColumns(20);
        jTextAreaCI.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jTextAreaCI.setForeground(new java.awt.Color(0, 51, 51));
        jTextAreaCI.setRows(5);
        jScrollPane5.setViewportView(jTextAreaCI);

        javax.swing.GroupLayout jPanelCILayout = new javax.swing.GroupLayout(jPanelCI);
        jPanelCI.setLayout(jPanelCILayout);
        jPanelCILayout.setHorizontalGroup(
            jPanelCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        jPanelCILayout.setVerticalGroup(
            jPanelCILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        jTabbedPaneTypes.addTab("Código Interno", jPanelCI);

        jPanelPrincipal.add(jTabbedPaneTypes, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 520, 470));

        jTextAreaErrores.setEditable(false);
        jTextAreaErrores.setBackground(new java.awt.Color(150, 150, 150));
        jTextAreaErrores.setColumns(20);
        jTextAreaErrores.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        jTextAreaErrores.setForeground(new java.awt.Color(153, 0, 0));
        jTextAreaErrores.setRows(5);
        jScrollPane6.setViewportView(jTextAreaErrores);

        javax.swing.GroupLayout jPanelErroresLayout = new javax.swing.GroupLayout(jPanelErrores);
        jPanelErrores.setLayout(jPanelErroresLayout);
        jPanelErroresLayout.setHorizontalGroup(
            jPanelErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
        );
        jPanelErroresLayout.setVerticalGroup(
            jPanelErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );

        jTabbedPaneResultados.addTab("Errores", jPanelErrores);

        jTextAreaResultados.setBackground(new java.awt.Color(150, 150, 150));
        jTextAreaResultados.setColumns(20);
        jTextAreaResultados.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        jTextAreaResultados.setForeground(new java.awt.Color(0, 51, 51));
        jTextAreaResultados.setRows(5);
        jScrollPane7.setViewportView(jTextAreaResultados);

        javax.swing.GroupLayout jPanelResultadosLayout = new javax.swing.GroupLayout(jPanelResultados);
        jPanelResultados.setLayout(jPanelResultadosLayout);
        jPanelResultadosLayout.setHorizontalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
        );
        jPanelResultadosLayout.setVerticalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );

        jTabbedPaneResultados.addTab("Resultados", jPanelResultados);

        jPanelPrincipal.add(jTabbedPaneResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 830, 160));

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N

        jMenuArchivo.setText("Archivo");

        jMenuItemArchivo.setText("Abrir");
        jMenuItemArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemArchivoActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemArchivo);

        jMenuItemGuardar.setText("Guardar");
        jMenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemGuardar);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBar1.add(jMenuArchivo);

        jMenuEditar.setText("Editar");
        jMenuBar1.add(jMenuEditar);

        jMenuFormato.setText("Formato");
        jMenuBar1.add(jMenuFormato);

        jMenuCompilar.setText("Compilar");

        jMenuItemComp.setText("Compilar");
        jMenuItemComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCompActionPerformed(evt);
            }
        });
        jMenuCompilar.add(jMenuItemComp);

        jMenuItemDebug.setText("Debug");
        jMenuCompilar.add(jMenuItemDebug);

        jMenuBar1.add(jMenuCompilar);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemArchivoActionPerformed
        // TODO add your handling code here:
        if (seleccionar.showDialog(this, "Abrir") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionar.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith("txt")) {
                    String documento = abrirArchivo(archivo);
                    jTextPaneCodigo.setText(documento);
                } else {
                    JOptionPane.showMessageDialog(this, "Archivo inválido");
                }
            }
        }
    }//GEN-LAST:event_jMenuItemArchivoActionPerformed

    private void jMenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarActionPerformed
        // TODO add your handling code here:
        if (seleccionar.showDialog(this, "Guardar") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionar.getSelectedFile();
            if (archivo.getName().endsWith("txt")) {
                String doc = jTextPaneCodigo.getText();
                String msj = guardarArchivo(archivo, doc);
                if (msj != null) {
                    JOptionPane.showMessageDialog(this, msj);
                } else {
                    JOptionPane.showMessageDialog(this, "Archivo Incompatible");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Guardar Documento");
            }
        }
    }//GEN-LAST:event_jMenuItemGuardarActionPerformed

    private void jMenuItemCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCompActionPerformed
        // TODO add your handling code here:
        jTextAreaErrores.setText("");
        System.out.println("Si compila");
        PythonInterpreter automata = new PythonInterpreter();
        String[] args = jTextPaneCodigo.getText().split("\r?\n");
        String Args = "[";
        for (int i = 0; i < args.length; i++) {
            Args += "'" + args[i] + "'";
            if (!(i == (args.length - 1))) {
                Args += ",";
            }
        }
        Args += "]";
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PrintStream imp = new PrintStream(out);
        automata.setOut(imp);
        automata.exec("import sys\n" + "sys.argv=" + Args);
        automata.execfile(direccionDanielAuto);
        //automata.execfile(direccionAlexisAuto);
        String output = out.toString();
        jTextAreaLexico.setText(output);
        try {
            abrirContenido(direccionDanielError);
            //abrirContenido(direccionAlexisError);
        } catch (IOException ex) {
            Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemCompActionPerformed
    //Funciones varias
    private void pintarColores() {
        final StyleContext contexto = StyleContext.getDefaultStyleContext();
        //colores
        final AttributeSet colorRojo = contexto.addAttribute(contexto.getEmptySet(), StyleConstants.Foreground, new Color(156, 37, 21));
        final AttributeSet colorAzul = contexto.addAttribute(contexto.getEmptySet(), StyleConstants.Foreground, new Color(107, 165, 209));
        final AttributeSet colorVerde = contexto.addAttribute(contexto.getEmptySet(), StyleConstants.Foreground, new Color(1, 167, 36));
        //Fin Primarios
        final AttributeSet colorAmarillo = contexto.addAttribute(contexto.getEmptySet(), StyleConstants.Foreground, new Color(211, 244, 70));
        final AttributeSet colorAqua = contexto.addAttribute(contexto.getEmptySet(), StyleConstants.Foreground, new Color(35, 210, 204));
        final AttributeSet colorGrisClaro = contexto.addAttribute(contexto.getEmptySet(), StyleConstants.Foreground, new Color(120, 129, 163));
        final AttributeSet colorBase = contexto.addAttribute(contexto.getEmptySet(), StyleConstants.Foreground, new Color(0,51,102));
        //Fin Colores
        DefaultStyledDocument documento = new DefaultStyledDocument() {

            @Override
            public void postRemoveUpdate(AbstractDocument.DefaultDocumentEvent chng) {
                try {
                    super.postRemoveUpdate(chng);
                    String text = getText(0, getLength());
                    Matcher matcher;
                    //Palabras Reservadas
                    Pattern pReservadas = Pattern.compile("\\b(main|if|IF|else|ELSE|end|END|do|DO|while|WHILE|then|THEN|repeat|REPEAT|until|UNTIL|cin|cout|print|def)\\b");
                    matcher = pReservadas.matcher(text);
                    while (matcher.find()) {
                        setCharacterAttributes(matcher.start(), matcher.end() - matcher.start(), colorAzul, true);
                    }
                    //Valores Numericos
                    Pattern numeros = Pattern.compile("\\b(-?\\d+(\\.\\d+)?)\\b");
                    matcher = numeros.matcher(text);
                    while (matcher.find()) {
                        setCharacterAttributes(matcher.start(), matcher.end() - matcher.start(), colorVerde, true);
                    }
                    //Booleanos
                    Pattern booleano = Pattern.compile("\\b(true|TRUE|false|FALSE)\\b");
                    matcher = booleano.matcher(text);
                    while (matcher.find()) {
                        setCharacterAttributes(matcher.start(), matcher.end() - matcher.start(), colorRojo, true);
                    }
                    //Tipos de Datos
                    Pattern tDatos = Pattern.compile("\\b(int|INT|real|REAL|boolean|BOOLEAN)\\b");
                    matcher = tDatos.matcher(text);
                    while (matcher.find()) {
                        setCharacterAttributes(matcher.start(), matcher.end() - matcher.start(), colorAqua, true);
                    }
                    //Operadores
                    Pattern operadores = Pattern.compile("[+-/=<>!]");
                    matcher = operadores.matcher(text);
                    while (matcher.find()) {
                        setCharacterAttributes(matcher.start(), matcher.end() - matcher.start(), colorAmarillo, true);
                    }
                    //Comentarios
                    Pattern comentarios = Pattern.compile("\\//\\/.\\#");
                    matcher = comentarios.matcher(text);
                    while (matcher.find()) {
                        setCharacterAttributes(matcher.start(), matcher.end() - matcher.start(), colorGrisClaro, true);
                    }
                    //Cometarios Multiples
                    Pattern mComentarios = Pattern.compile("\\/*\\*.*?\\*/\\//", Pattern.DOTALL);
                    matcher = mComentarios.matcher(text);
                    while (matcher.find()) {
                        setCharacterAttributes(matcher.start(), matcher.end() - matcher.start(), colorGrisClaro, true);
                    }

                } catch (BadLocationException ex) {
                    Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            //Pintamos los datos
            @Override
            public void insertString(int offset, String llave, AttributeSet at) throws BadLocationException {
                super.insertString(offset, llave, at);
                String text = getText(0, getLength());
                setCharacterAttributes(0, getLength(), colorBase, true);
                Matcher matcher;
                //Palabras Reservadas
                Pattern pReservadas = Pattern.compile("\\b(main|if|IF|else|ELSE|end|END|do|DO|while|WHILE|then|THEN|repeat|REPEAT|until|UNTIL|cin|cout|print|def)\\b");
                matcher = pReservadas.matcher(text);
                while (matcher.find()) {
                    setCharacterAttributes(matcher.start(), matcher.end() - matcher.start(), colorAzul, true);
                }
                //Valores Numericos
                Pattern numeros = Pattern.compile("\\b(-?\\d+(\\.\\d+)?)\\b");
                matcher = numeros.matcher(text);
                while (matcher.find()) {
                    setCharacterAttributes(matcher.start(), matcher.end() - matcher.start(), colorVerde, true);
                }
                //Booleanos
                Pattern booleano = Pattern.compile("\\b(true|TRUE|false|FALSE)\\b");
                matcher = booleano.matcher(text);
                while (matcher.find()) {
                    setCharacterAttributes(matcher.start(), matcher.end() - matcher.start(), colorRojo, true);
                }
                //Tipos de Datos
                Pattern tDatos = Pattern.compile("\\b(int|INT|real|REAL|boolean|BOOLEAN)\\b");
                matcher = tDatos.matcher(text);
                while (matcher.find()) {
                    setCharacterAttributes(matcher.start(), matcher.end() - matcher.start(), colorAqua, true);
                }
                //Operadores
                Pattern operadores = Pattern.compile("[+-/=<>!]");
                matcher = operadores.matcher(text);
                while (matcher.find()) {
                    setCharacterAttributes(matcher.start(), matcher.end() - matcher.start(), colorAmarillo, true);
                }
                // Comentarios
                Pattern comentarios = Pattern.compile("\\/\\/[^\\n]*");
                matcher = comentarios.matcher(text);
                while (matcher.find()) {
                    setCharacterAttributes(matcher.start(), matcher.end() - matcher.start(), colorGrisClaro, true);
                }

                // Comentarios Multiples
                Pattern mComentarios = Pattern.compile("\\/\\*.*?\\*\\/", Pattern.DOTALL);
                matcher = mComentarios.matcher(text);
                while (matcher.find()) {
                    setCharacterAttributes(matcher.start(), matcher.end() - matcher.start(), colorGrisClaro, true);
                }
            }

        };

        String temp = this.jTextPaneCodigo.getText();
        this.jTextPaneCodigo.setStyledDocument(documento);
        this.jTextPaneCodigo.setText(temp);

    }
    //Fin pintar colores
    
        private void touchdown(java.awt.event.KeyEvent ev) throws IOException, FileNotFoundException {
        int keyCode = ev.getKeyCode();
        if ((keyCode >= 65 && keyCode <= 90) || (keyCode >= 48 && keyCode <= 57) || (keyCode >= 97 && keyCode <= 122)
                || (keyCode != 37 && !(keyCode >= 37 && keyCode <= 40) && !(keyCode >= 16 && keyCode <= 18)
                && keyCode != 524 && keyCode != 20)) {
            if (!getTitle().contains("*")) {
                setTitle(getTitle() + "*");
            }
            //if (ev.getKeyCode() == KeyEvent.VK_ENTER) {
           /* System.out.println("Has entrado al key event");
            PythonInterpreter automata = new PythonInterpreter();
            String[] args = jTextPaneCodigo.getText().split("\r?\n");
            String Args = "[";
            for (int i = 0; i < args.length; i++) {
                Args += "'" + args[i] + "'";
                if (!(i == (args.length - 1))) {
                    Args += ",";
                }
            }
            Args += "]";
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            PrintStream imp = new PrintStream(out);
            automata.setOut(imp);
            automata.exec("import sys\n" + "sys.argv=" + Args);
            automata.execfile("C:\\Users\\bukch\\Desktop\\univrsidad\\compilador\\Corvex\\python\\automata.py");
            String output = out.toString();
            jTextAreaLexico.setText(output);
            abrirContenido("C:\\Users\\bukch\\Desktop\\univrsidad\\compilador\\Corvex\\error.txt");

            //}*/
        }
    }//Fin touchdown

         public void abrirContenido(String ruta) throws FileNotFoundException, IOException {
        String cadena;
        StringBuilder contenido = new StringBuilder();

        try (BufferedReader br = new BufferedReader(new FileReader(ruta))) {
            while ((cadena = br.readLine()) != null) {
                System.out.println("Se ha entrado a abrir el contenido");
                System.out.println(cadena);
                jTextAreaErrores.append(cadena + "\n");
                contenido.append(cadena).append("\n");
            }
        }

        // Sobrescribir el archivo de texto con el contenido en blanco
        try (PrintWriter pw = new PrintWriter(new FileWriter(ruta))) {
            pw.print("");
        }

        FileWriter fw = new FileWriter(ruta);
        fw.write(contenido.toString());
        fw.close();
    }// Fin Abrir contenido
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCompilar;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuFormato;
    private javax.swing.JMenuItem jMenuItemArchivo;
    private javax.swing.JMenuItem jMenuItemComp;
    private javax.swing.JMenuItem jMenuItemDebug;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JPanel jPanelCI;
    private javax.swing.JPanel jPanelErrores;
    private javax.swing.JPanel jPanelLexico;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelResultados;
    private javax.swing.JPanel jPanelSemantico;
    private javax.swing.JPanel jPanelSintactico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPaneResultados;
    private javax.swing.JTabbedPane jTabbedPaneTypes;
    private javax.swing.JTextArea jTextAreaCI;
    private javax.swing.JTextArea jTextAreaErrores;
    private javax.swing.JTextArea jTextAreaLexico;
    private javax.swing.JTextArea jTextAreaResultados;
    private javax.swing.JTextArea jTextAreaSemantico;
    private javax.swing.JTextArea jTextAreaSintactoco;
    private javax.swing.JTextPane jTextPaneCodigo;
    // End of variables declaration//GEN-END:variables
}
